version: '2'

volumes:
  mysql_data:

services:
  codebase:
    # build: .
    image: busybox
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracker
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  webserver:
    build: containers/webserver
    ports:
      - 9000:80
    volumes_from:
      - codebase
    links:
      - db
    environment:
      STORAGE_DRIVER: mysql
      MYSQL_DBNAME: tracker
      MYSQL_HOSTNAME: db
      MYSQL_USERNAME: username
      MYSQL_PASSWORD: password
    depends_on:
      - db

  cli:
    build: containers/webserver
    links:
      - db
      - webserver
    volumes_from:
      - codebase
    command: echo "CLI Initialised..."
    environment:
      STORAGE_DRIVER: ${STORAGE_DRIVER}
      MYSQL_DBNAME: tracker
      MYSQL_HOSTNAME: db
      MYSQL_USERNAME: username
      MYSQL_PASSWORD: password
    depends_on:
      - webserver
