version: '2'

volumes:
  mysql_data:

services:
  codebase:
    image: busybox
    volumes:
    - ./:/var/www/html

  db:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracker
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  webserver:
    build: .
    ports:
    - 8080:80
    volumes_from:
    - codebase
    links:
    - db
    environment:
      ENVIRONMENT: development
      STORAGE_DRIVER: mysql
      ADMIN_PASSWORD: testing123
      MYSQL_DBNAME: tracker
      MYSQL_HOSTNAME: db
      MYSQL_USERNAME: username
      MYSQL_PASSWORD: password
    depends_on:
    - db

  cli:
    build: .
    links:
    - db
    - webserver
    volumes_from:
    - codebase
    command: echo "CLI Initialised..."
    environment:
      ENVIRONMENT: development
      STORAGE_DRIVER: ${STORAGE_DRIVER}
      ADMIN_PASSWORD: testing123
      MYSQL_DBNAME: tracker
      MYSQL_HOSTNAME: db
      MYSQL_USERNAME: username
      MYSQL_PASSWORD: password
      SITE_URL: http://webserver/
    depends_on:
    - webserver
