version: '2'

volumes:
  mysql_data:

services:
  db:
    image: mariadb
    volumes:
    - mysql_data:/var/lib/mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracker
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  webserver:
    image: ${DEPLOYMENT_IMAGE}
    ports:
    - 80:80
    links:
    - db
    environment:
      STORAGE_DRIVER: mysql
      MYSQL_DBNAME: tracker
      MYSQL_HOSTNAME: db
      MYSQL_USERNAME: username
      MYSQL_PASSWORD: password
    depends_on:
    - db
