---
resource_types:
- name: simple-s3
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple
    tag: latest

resources:
- name: github-repository
  type: git
  source:
    uri: git@github.com:tomphp/time-tracker.git
    private_key: {{github_deploy_private_key}}
    branch: cf

- name: composer-cache
  type: simple-s3
  source:
    bucket: ci-composer-cache
    access_key_id: {{s3_composer_cache_key}}
    secret_access_key: {{s3_composer_cache_secret}}
    path: time-tracker
    options:
      - "--exclude '*'"
      - "--include 'build-dir/vendor-cache.tgz'"

- name: e2e-tests-platform
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: tom@codept.com
    password: {{cf_password}}
    organization: example-test
    space: e2e-tests
    skip_cert_check: false

- name: deploy-platform
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: tom@codept.com
    password: {{cf_password}}
    organization: example-test
    space: deployment
    skip_cert_check: false

jobs:
- name: unit-tests
  public: false
  plan:
  - aggregate:
    - get: github-repository
      trigger: true
    - get: composer-cache
  - task: composer install
    file: github-repository/ci/composer_install.yml
    privileged: true
    params: { MODE: development }
  - aggregate:
    - task: run-tests
      file: github-repository/ci/unit-tests.yml
    - put: composer-cache

- name: deploy-e2e
  public: false
  serial: true
  plan:
  - get: github-repository
    trigger: true
    passed: [unit-tests]
  - put: e2e-tests-platform
    params:
      manifest: github-repository
      current_app_name: time-tracker-e2e-tests
      environment_variables:
        STORAGE_DRIVER: mysql

- name: e2e-tests
  public: false
  serial: true
  plan:
  - aggregate:
    - get: github-repository
      trigger: true
      passed: [deploy-e2e]
    - get: composer-cache

  - task: composer install
    file: github-repository/ci/composer_install.yml
    privileged: true
    params: { MODE: developement }

  - task: Run end-to-end tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: tomoram/time-tracker-php }
      inputs:
      - name: build-dir
      - name: deployment-image
      params:
        SITE_URL: http://time-tracker-e2e-tests.cfapps.io/
      run:
        dir: build-dir
        path: sh
        args:
        - -exc
        - |
          export STORAGE_DRIVER=mysql

          vendor/bin/phpunit --testsuite mysql
          vendor/bin/behat -p e2e

- name: deploy
  public: false
  serial: true
  plan:
  - get: github-repository
    trigger: true
    passed: [e2e-tests]
  - put: deploy-platform
    params:
      manifest: github-repository
      current_app_name: time-tracker-app
      environment_variables:
        STORAGE_DRIVER: mysql
