---
resources:
- name: github-repository
  type: git
  source:
    uri: git@github.com:tomphp/time-tracker.git
    #skip_ssl_verification: true
    private_key: {{github_deploy_private_key}}

jobs:
- name: unit-tests
  public: true
  plan:
  - get: github-repository
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: tomoram/time-tracker-php}
      inputs:
      - name: github-repository
      run:
        path: github-repository/ci/unit.sh

- name: integration
  plan:
  - get: github-repository
    passed: [unit-tests]
    trigger: true
  - task: Run integration tests
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind
      inputs:
        - name: github-repository
      run:
        path: sh
        args:
          - -exc
          - |
            source /docker-lib.sh
            start_docker

            # docker load -i tomphp/time-tracker-php
            # docker images

            cd github-repository
            export STORAGE_DRIVER=mysql

            docker-compose up -d
            docker ps

            docker-compose run --rm cli composer install
            docker-compose run --rm cli vendor/bin/phinx migrate -e testing
            docker-compose run --rm cli vendor/bin/phpunit --testsuite mysql
            docker-compose run --rm cli vendor/bin/behat -p e2e

            docker-compose down
            docker volume rm $(docker volume ls -q)

            cd ..
