---
resources:
- name: github-repository
  type: git
  source:
    uri: git@github.com:tomphp/time-tracker.git
    #skip_ssl_verification: true
    private_key: {{github_deploy_private_key}}

jobs:
- name: unit-tests
  public: false
  plan:
  - get: github-repository
    trigger: true
  - task: composer install
    file: github-repository/ci/composer_install.yml
    privileged: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: tomoram/time-tracker-php}
      inputs:
      - name: build-dir
      run:
        path: build-dir/ci/unit.sh

- name: mysql-tests
  public: false
  plan:
  - get: github-repository
    trigger: true
  - task: composer install
    file: github-repository/ci/composer_install.yml
    privileged: true
  - task: run-tests
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind
      inputs:
      - name: build-dir
      run:
        path: sh
        args:
          - -exc
          - |
            source /docker-lib.sh
            start_docker

            # docker load -i tomphp/time-tracker-php
            # docker images

            cd build-dir
            export STORAGE_DRIVER=mysql

            docker-compose up -d
            docker ps

            sleep 20 # Wait for MySQL to initialise

            docker-compose run --rm cli vendor/bin/phinx migrate -e testing
            docker-compose run --rm cli vendor/bin/phpunit --testsuite mysql

            docker-compose down
            docker volume rm $(docker volume ls -q)

- name: e2e-tests
  public: false
  plan:
  - get: github-repository
    passed: [unit-tests, mysql-tests]
    trigger: true
  - task: composer install
    file: github-repository/ci/composer_install.yml
    privileged: true
  - task: Run end-to-end tests
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind
      inputs:
        - name: build-dir
      run:
        path: sh
        args:
          - -exc
          - |
            source /docker-lib.sh
            start_docker

            # docker load -i tomphp/time-tracker-php
            # docker images

            cd build-dir
            export STORAGE_DRIVER=mysql

            docker-compose up -d
            docker ps

            sleep 20 # Wait for MySQL to initialise

            docker-compose run --rm cli cat /etc/hosts
            docker-compose run --rm cli ping -c 5 db
            docker-compose run --rm cli vendor/bin/phinx migrate -e testing
            docker-compose run --rm cli vendor/bin/behat -p e2e

            docker-compose down
            docker volume rm $(docker volume ls -q)
