---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: composer/composer

inputs:
  - name: github-repository

outputs:
  - name: build-dir

run:
  path: composer_install.sh
  params:
    SOURCE: github-repository
    DESTINATION: build-dir
    MODE: production
