---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: composer/composer

inputs:
  - name: github-repository
  - name: composer-cache

outputs:
  - name: build-dir

params:
  SOURCE: github-repository
  DESTINATION: build-dir
  MODE: development
  CACHE_FILE: composer-cache/time-tracker-vendor.tgz

run:
  path: github-repository/ci/composer_install.sh
